require 'stripemetrics/cli/commands/register.rb'
require 'stripemetrics/cli/commands/login.rb'
require 'stripemetrics/cli/commands/ping.rb'
require 'stripemetrics/cli/commands/import.rb'
require 'stripemetrics/cli/commands/refresh.rb'
require 'stripemetrics/cli/commands/metric.rb'